version: '{build}'
branches:
  only:
  - ninja_all
environment:
  USE_CLANG_COMPLETER: true
  matrix:
  - msvc: 14
    arch: 64
    python: 35
install:
  - ci\appveyor\appveyor_install.bat
build_script:
  - python build.py --all
  - python run_tests.py --msvc %MSVC%
# Disable automatic tests
test: off
cache:
  - '%LOCALAPPDATA%\pip\cache'  # Python packages from pip
  - '%APPDATA%\npm-cache'  # Node packages from npm
  - '%USERPROFILE%\.cargo'  # Cargo package deps
  - '%APPVEYOR_BUILD_FOLDER%\clang_archives'  # Clang downloads
  - '%APPVEYOR_BUILD_FOLDER%\third_party\racerd\target'  # Racerd compilation
